version: '3.8'

# Services
services:

  # Nginx Service
  nginx:
    image: nginx:1.19-alpine
    ports:
      - "80:80"
    volumes:
      - ./src/backend:/var/www/backend
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend

  # Backend Service
  backend:
    build:
      context: ./src/backend
      target: backend
      args:
        HOST_UID: $HOST_UID
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
      - ./.docker/backend/init:/opt/files/init
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  # Frontend Service
  frontend:
    build:
      context: ./src/frontend
    working_dir: /var/www/frontend
    volumes:
      - ./src/frontend:/var/www/frontend
    depends_on:
      - backend

#  # Frontend Setup Service (ONLY DEV)
#  frontend-setup:
#    build:
#      context: ./.docker/frontend
#      dockerfile: Setup.Dockerfile
#      args:
#        HOST_UID: $HOST_UID
#    working_dir: /var/www/frontend
#    volumes:
#      - ./src/frontend:/var/www/frontend


  # MySQL Service
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    volumes:
      - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 10

  # Redis Service
  redis:
    image: redis:6-alpine
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redisdata:/data

  # Worker Service
  worker:
    build:
      context: ./src/backend
      target: worker
      args:
        HOST_UID: $HOST_UID
    working_dir: /var/www/backend
    volumes:
      - ./src/backend:/var/www/backend
    depends_on:
      - backend

# Volumes
volumes:

  mysqldata:

  redisdata: